[character]
success_symbol = "[](bold fg:183) "
error_symbol = "[](bold red) "

[username]
show_always = true
format = "[$user]($style)[@](fg:116)"
style_user = "fg:112"

[hostname]
ssh_only = false
style = "fg:36"

[directory]
truncate_to_repo = false
truncation_length = 0
style = "bold blue"

[ruby]
style = "bold fg:88"
symbol = "  "

[rust]
style = "bold fg:203"
symbol = " "

[git_branch]
style = "bold fg:216"

[perl]
disabled = true

[nodejs]
disabled = true
